(* Generated by: ocaml-crunch
   Creation date: Tue, 20 Feb 2024 17:49:09 GMT *)

module Internal = struct
  let d_4a2fa4dbae39a4d561d41b09af7ba84b = "(() => {\n  // output/frontend/frontend_js.mjs\n  function x(y, z) {\n    return y + z | 0;\n  }\n  console.log(\"hello world, from ocaml!!!! HELLO TWITCH. This is for anakinsonone\");\n  var name = \"Jane\";\n  var other = \"hello\";\n})();\n"

  let file_chunks = function
    | "frontend_js.js" | "/frontend_js.js" -> Some [ d_4a2fa4dbae39a4d561d41b09af7ba84b; ]
    | _ -> None

  let file_list = [ "frontend_js.js"; ]
end

let file_list = Internal.file_list

let read name =
  match Internal.file_chunks name with
  | None -> None
  | Some c -> Some (String.concat "" c)

let hash = function
  | "frontend_js.js" | "/frontend_js.js" -> Some "4a2fa4dbae39a4d561d41b09af7ba84b"
  | _ -> None

let size = function
  | "frontend_js.js" | "/frontend_js.js" -> Some 228
  | _ -> None
